spring:
  data:
    mongodb:
      database: instaclone_auth

server:
  port: 8081
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: 01bfa8caad6e257eae961a01d091be05

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic